I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\malyc\Documents\ren'py\renpy-7.4.2-sdk/renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "C:\Users\malyc\Documents\ren'py\renpy-7.4.2-sdk/renpy/main.py", line 567, in main
    renpy.dump.dump(False)
  File "C:\Users\malyc\Documents\ren'py\renpy-7.4.2-sdk/renpy/dump.py", line 260, in dump
    os.rename(new, filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
bored the game 1.0
Wed Mar 17 20:49:22 2021


Oops... I hope noone notices this.
